/**
 * SWOS420 — Upload NFT Metadata to Arweave
 *
 * Reads player data from a JSON export, generates ERC-721 metadata,
 * uploads images + JSON to Arweave via Turbo SDK, and outputs a
 * manifest mapping tokenId → ar:// URI.
 *
 * Usage:
 *   npx tsx upload_metadata.ts                     # Upload all players
 *   npx tsx upload_metadata.ts --dry-run           # Generate metadata without uploading
 *   npx tsx upload_metadata.ts --players 1001,1002 # Upload specific players
 *
 * Requires:
 *   - ARWEAVE_WALLET_PATH in .env (path to JWK keyfile)
 *   - Player data in ../../data/players_export.json (or --input flag)
 *   - Card images in ../../data/cards/ (generated by generate_cards.py)
 */

import { TurboFactory, TurboAuthenticatedClient } from "@ardrive/turbo-sdk";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import "dotenv/config";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ── Types ────────────────────────────────────────────────────────────

interface PlayerData {
  token_id: number;
  name: string;
  team: string;
  position: string;
  age: number;
  skills: {
    passing: number;
    velocity: number;
    heading: number;
    tackling: number;
    control: number;
    speed: number;
    finishing: number;
  };
  form: number;
  value: number;
  season_goals: number;
  total_goals: number;
}

interface ERC721Metadata {
  name: string;
  description: string;
  image: string;
  external_url: string;
  attributes: Array<{
    trait_type: string;
    value: number | string;
    max_value?: number;
    display_type?: string;
  }>;
}

interface ManifestEntry {
  tokenId: number;
  metadataUri: string;
  imageUri: string;
  metadataTxId: string;
  imageTxId: string;
}

// ── Config ───────────────────────────────────────────────────────────

const WALLET_PATH = process.env.ARWEAVE_WALLET_PATH || path.join(__dirname, "../../arweave-wallet.json");
const DATA_DIR = path.join(__dirname, "../../data");
const CARDS_DIR = path.join(DATA_DIR, "cards");
const INPUT_FILE = path.join(DATA_DIR, "players_export.json");
const OUTPUT_FILE = path.join(DATA_DIR, "metadata-manifest.json");

const DRY_RUN = process.argv.includes("--dry-run");
const PLAYER_FILTER = (() => {
  const idx = process.argv.indexOf("--players");
  if (idx === -1) return null;
  return process.argv[idx + 1]?.split(",").map(Number) ?? null;
})();

// ── Helpers ──────────────────────────────────────────────────────────

function buildMetadata(player: PlayerData, imageUri: string): ERC721Metadata {
  const skills = player.skills;
  return {
    name: player.name,
    description: `SWOS420 Player #${player.token_id} — ${player.team}. ${player.position}. The beautiful game, on-chain.`,
    image: imageUri,
    external_url: `https://swos420.xyz/player/${player.token_id}`,
    attributes: [
      { trait_type: "Passing", value: skills.passing, max_value: 15 },
      { trait_type: "Velocity", value: skills.velocity, max_value: 15 },
      { trait_type: "Heading", value: skills.heading, max_value: 15 },
      { trait_type: "Tackling", value: skills.tackling, max_value: 15 },
      { trait_type: "Control", value: skills.control, max_value: 15 },
      { trait_type: "Speed", value: skills.speed, max_value: 15 },
      { trait_type: "Finishing", value: skills.finishing, max_value: 15 },
      { trait_type: "Team", value: player.team },
      { trait_type: "Position", value: player.position },
      { trait_type: "Age", display_type: "number", value: player.age },
      { trait_type: "Form", display_type: "number", value: player.form },
      { trait_type: "Season Goals", display_type: "number", value: player.season_goals },
      { trait_type: "Total Goals", display_type: "number", value: player.total_goals },
      { trait_type: "Market Value", display_type: "number", value: player.value },
    ],
  };
}

async function uploadFile(
  turbo: TurboAuthenticatedClient,
  filePath: string,
  contentType: string,
  tags: Array<{ name: string; value: string }>
): Promise<string> {
  const fileSize = fs.statSync(filePath).size;
  const fileStream = fs.createReadStream(filePath);

  const result = await turbo.uploadFile({
    fileStreamFactory: () => fileStream as any,
    fileSizeFactory: () => fileSize,
    dataItemOpts: {
      tags: [{ name: "Content-Type", value: contentType }, ...tags],
    },
  });

  return result.id;
}

async function uploadBuffer(
  turbo: TurboAuthenticatedClient,
  buffer: Buffer,
  contentType: string,
  tags: Array<{ name: string; value: string }>
): Promise<string> {
  const { Readable } = await import("stream");
  const stream = Readable.from(buffer);

  const result = await turbo.uploadFile({
    fileStreamFactory: () => stream as any,
    fileSizeFactory: () => buffer.length,
    dataItemOpts: {
      tags: [{ name: "Content-Type", value: contentType }, ...tags],
    },
  });

  return result.id;
}

// ── Main ─────────────────────────────────────────────────────────────

async function main() {
  console.log("🏟️  SWOS420 Arweave Metadata Uploader");
  console.log(`   Mode: ${DRY_RUN ? "DRY RUN (no uploads)" : "LIVE UPLOAD"}`);
  console.log("");

  // Load player data
  if (!fs.existsSync(INPUT_FILE)) {
    console.error(`❌ Player data not found at ${INPUT_FILE}`);
    console.error("   Run: python scripts/export_players.py first");
    process.exit(1);
  }

  const players: PlayerData[] = JSON.parse(fs.readFileSync(INPUT_FILE, "utf-8"));
  const filtered = PLAYER_FILTER
    ? players.filter((p) => PLAYER_FILTER.includes(p.token_id))
    : players;

  console.log(`📋 ${filtered.length} players to process`);

  if (DRY_RUN) {
    // Just generate metadata and show it
    for (const player of filtered) {
      const metadata = buildMetadata(player, `ar://<pending>`);
      console.log(`\n--- Player #${player.token_id}: ${player.name} ---`);
      console.log(JSON.stringify(metadata, null, 2));
    }
    console.log("\n✅ Dry run complete. No uploads made.");
    return;
  }

  // Load Arweave wallet
  if (!fs.existsSync(WALLET_PATH)) {
    console.error(`❌ Wallet keyfile not found at ${WALLET_PATH}`);
    console.error("   Create one at https://arweave.app or via ArweaveKit");
    process.exit(1);
  }

  const jwk = JSON.parse(fs.readFileSync(WALLET_PATH, "utf-8"));
  const turbo = TurboFactory.authenticated({ privateKey: jwk });

  // Check balance
  const balance = await turbo.getBalance();
  console.log(`💰 Turbo balance: ${balance.winc} winc`);

  const manifest: ManifestEntry[] = [];

  for (const player of filtered) {
    console.log(`\n⚽ Processing #${player.token_id}: ${player.name}...`);

    // 1. Upload image (SVG card)
    let imageTxId = "";
    const cardPath = path.join(CARDS_DIR, `${player.token_id}.svg`);
    if (fs.existsSync(cardPath)) {
      console.log("   📷 Uploading card image...");
      imageTxId = await uploadFile(turbo, cardPath, "image/svg+xml", [
        { name: "App-Name", value: "SWOS420" },
        { name: "Player-Id", value: String(player.token_id) },
        { name: "Type", value: "player-card" },
      ]);
      console.log(`   ✅ Image: ar://${imageTxId}`);
    } else {
      console.log(`   ⚠️  No card image found at ${cardPath} — skipping image`);
    }

    // 2. Build + upload metadata JSON
    const imageUri = imageTxId ? `ar://${imageTxId}` : "";
    const metadata = buildMetadata(player, imageUri);
    const metadataBuffer = Buffer.from(JSON.stringify(metadata, null, 2));

    console.log("   📄 Uploading metadata JSON...");
    const metadataTxId = await uploadBuffer(turbo, metadataBuffer, "application/json", [
      { name: "App-Name", value: "SWOS420" },
      { name: "Player-Id", value: String(player.token_id) },
      { name: "Type", value: "player-metadata" },
    ]);
    console.log(`   ✅ Metadata: ar://${metadataTxId}`);

    manifest.push({
      tokenId: player.token_id,
      metadataUri: `ar://${metadataTxId}`,
      imageUri: imageTxId ? `ar://${imageTxId}` : "",
      metadataTxId,
      imageTxId,
    });
  }

  // Write manifest
  fs.writeFileSync(OUTPUT_FILE, JSON.stringify(manifest, null, 2));
  console.log(`\n📦 Manifest written to ${OUTPUT_FILE}`);
  console.log(`   ${manifest.length} players uploaded to Arweave ✅`);
  console.log("\nNext step: python scripts/arweave/set_token_uris.py");
}

main().catch(console.error);
